# =========================================================
# Hugo Configuration
# Project: RespiraFibre
# =========================================================

title: "Continuous Respiratory Monitoring"
baseURL: "https://www.respirafibre.com/"
languageCode: "en-gb"
copyright: "© 2025 RespiraFibre. All rights reserved."
assetDir: "assets"

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
    # - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    # - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal

pagination:
  pagerSize: 10

############################
## PAGE OPTIONS (cascade)
############################
cascade:
  - _target:
      path: /posts/**
      kind: page
    pager: true
    editable: false
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: false
    show_related: true
    share: true
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  - _target:
      path: /posts/*
      kind: section
    view: date-title-summary
    sort_by: date
    sort_ascending: false

############################
## LANGUAGE
############################
defaultContentLanguage: "en"
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## PERMALINKS
############################
permalinks:
  posts: "/posts/:slug/"
  tags: "/tag/:slug/"
  categories: "/category/:slug/"
  authors: "/author/:slug/"

############################
## SITE GENERATION
############################
build:
  writeStats: true

enableGitInfo: true
summaryLength: 30
enableEmoji: true
enableRobotsTXT: true
disableAliases: true
footnotereturnlinkcontents: "<sup>^</sup>"
ignoreFiles:
  - "\\.ipynb$"
  - "\\.ipynb_checkpoints$"
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"

############################
## OUTPUTS
############################
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]

############################
## IMAGING
############################
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture

############################
## TAXONOMIES
############################
taxonomies:
  tag: tags
  category: categories
  author: authors

############################
## MARKUP & SYNTAX HIGHLIGHTING
############################
markup:
  highlight:
    lineNos: false
    style: github
  goldmark:
    renderer:
      unsafe: true

############################
## SECURITY
############################
security:
  enableInlineShortcodes: true
  exec:
    # Allow Hugo to call required tools in CI:
    allow:
      - "go"
      - "bash"
      - "git"          # needed for enableGitInfo
      - "tailwindcss"  # needed by the Tailwind pipeline
    osEnv:
      - '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$'
  funcs:
    getenv: ["HUGO_ENV", "WC_ENV"]
  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']

############################
## SITEMAP
############################
sitemap:
  changefreq: weekly
  priority: 0.7
  filename: "sitemap.xml"

############################
## TIMEOUT
############################
timeout: 600000
