# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/

# =======================
# Appearance
# =======================
appearance:
  mode: light              # or "system" if you want dark mode auto
  color: indigo
  # ----------------------------

# =======================
# Custom CSS overrides
# =======================
customCSS:
  - "css/custom.css"

# =======================
# SEO / Marketing
# =======================
marketing:
  seo:
    site_type: Organization
    org_name: "RespiraFibre"
    local_business_type: ""
    description: "RespiraFibre turns everyday oxygen masks and nasal cannulas into life-saving sensors — continuous, unobtrusive respiratory monitoring to detect deterioration earlier."
    twitter: ""              # your @handle if you have one (no @)
  analytics:
    google_analytics: ""    # G-XXXXXXXXXX
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""              # Search Console verification
    baidu: ""

# =======================
# Header / Navbar
# =======================
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      filename: "RespiraFibreLogo_Website.svg"
    button:
      enable: false
      text: "Contact Us"
      url: "/contact/"
    show_search: false      # turn on later if you add a blog/search
    show_theme_chooser: false

# (Nav links live in config/_default/menus.yaml — see below)

# =======================
# Footer
# =======================
footer:
  copyright:
    notice: "© {year} RespiraFibre. All rights reserved."

# =======================
# Localization
# =======================
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
